#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# 本地 .env.supabase 保存捕获到的值（仓库根目录下）
ENV_FILE="/Users/ncicheng/crewAI/MyGame/.env.supabase"

# 需要写入 GitHub 的变量（ncicheng/mygame）
GH_REPO="ncicheng/mygame"
GH_VARS_URL="https://github.com/ncicheng/mygame/settings/variables/actions"

# 供用户在 SQL Editor 粘贴的 schema 文件
SCHEMA_FILE="/Users/ncicheng/crewAI/MyGame/supabase/schema.sql"

banner "Supabase 上线配置"

# ── Stage 1: 登录/创建 Supabase ────────────────────────────────────────────
stage "登录 / 创建 Supabase"
say "这一步确保你已登录 Supabase 控制台，没有账号则先注册。"
open_url "https://supabase.com/dashboard"
step "在打开的页面用你的账号登录；若没有账号，先点 Sign up 注册。"
step "登录成功后会看到 Dashboard（项目列表）。"
pause "已登录 Supabase 控制台后，按 Enter 继续。"

# ── Stage 2: New project ───────────────────────────────────────────────────
stage "New project（免费）"
say "创建一个新的 Supabase 项目，用于承载 MyGame 的数据库。"
open_url "https://supabase.com/dashboard/projects"
step "点击右上角 New project（或 New empty project）。"
step "选择 Organization（没有则新建一个）。"
step "Name 填 mygame（可自定，仅展示用）。"
step "设置一个 Database password（务必记牢，后续连接要用）。"
step "选择 Region（建议选离你最近的节点）。"
step "确认免费套餐后点 Create new project。"
note "项目创建/配置需要几分钟，等它 Provisioning 完成、状态变为绿色后继续。"
pause "项目已创建完成（数据库可用）后，按 Enter 继续。"

# ── Stage 3: 获取 Project URL + anon key ───────────────────────────────────
stage "获取 Project URL + anon key"
say "从项目设置里拿到前端要用的连接信息（URL 与 anon key）。"
open_url "https://supabase.com/dashboard/projects"
step "进入刚才创建的项目（mygame）Dashboard。"
step "左侧菜单 → Project Settings → API。"
step "复制 Project URL（形如 https://xxxxxxxx.supabase.co）。"
ask SUPABASE_URL "粘贴 Project URL："
step "在 API 页的 Project API keys 里复制 anon public 那一行的 key（非 secret 的 public key）。"
ask SUPABASE_ANON_KEY "粘贴 anon public key："
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
pause "URL 与 anon key 已保存到 .env.supabase 后，按 Enter 继续。"

# ── Stage 4: 运行 schema.sql ───────────────────────────────────────────────
stage "运行 schema.sql"
say "在项目的 SQL Editor 里执行 schema 文件，建库建表并启用 RLS。"
open_url "https://supabase.com/dashboard/projects"
step "进入 mygame 项目 → 左侧菜单 SQL Editor（SQL 编辑器）。"
step "新建查询（New query），打开本地文件："
note "  $SCHEMA_FILE"
note "  该文件包含全部建表、外键、RLS 策略与『新用户自动播种』触发器。"
step "把文件全部内容粘贴进编辑器，然后点击 Run（运行）。"
note "全部 DDL 与 RLS 策略会一次执行；无报错即成功。"
pause "schema 已在 SQL Editor 运行成功（无报错）后，按 Enter 继续。"

# ── Stage 5: 设置 GitHub variables ─────────────────────────────────────────
stage "设置 GitHub variables"
say "把 URL 与 anon key 写成 GitHub Actions 变量，供 Pages 部署使用。"
say "（anon key 在浏览器应用里本就是公开的，故用变量而非 secret。）"
set_var VITE_SUPABASE_URL "$SUPABASE_URL"
set_var VITE_SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
if (( ${#SKIPPED[@]} )); then
  warn "当前 gh token 可能权限不足，variables 未写入。请按以下方式在网页手动设置："
  open_url "$GH_VARS_URL"
  step "点击 New repository variable，新增 2 个变量："
  note "  1) Name: VITE_SUPABASE_URL   Value: $SUPABASE_URL"
  note "  2) Name: VITE_SUPABASE_ANON_KEY  Value: $SUPABASE_ANON_KEY"
  note "  每个变量填好后点击 Add variable 保存。"
  pause "GitHub variables 已设置（VITE_SUPABASE_URL + VITE_SUPABASE_ANON_KEY）后，按 Enter 继续。"
else
  say "两个 GitHub variable 已写入 $GH_REPO。"
fi

# ── Stage 6: 提示触发部署 ──────────────────────────────────────────────────
stage "触发部署"
say "最后一步：把代码推到 main，让 GitHub Actions 用上面的变量部署前端到 Pages。"
step "在 MyGame 仓库提交并推送改动到 main 分支。"
step "推送后进入 Actions 页，确认前端部署 workflow 运行成功。"
open_url "https://github.com/ncicheng/mygame/actions"
note "部署完成后，访问 GitHub Pages 站点即可用 Supabase URL + anon key 联调。"
pause "已 push 到 main 并确认 Actions 部署成功，按 Enter 完成。"

finish
